### ISSUE TITLE
Accept API_IPS configuration as an environment variable

### ISSUE THREAD

**Issue by xendarboh** [SecureSECO/SearchSECOController#33]
DatabaseAPI IPs are read directly from the `.env` file, creating challenges within a docker container context as the docker image must be built with the configuration.

The latest [searchseco/controller](https://hub.docker.com/r/searchseco/controller) Docker Image on Docker Hub currently has an error within it's `.env` file:

```sh
docker pull searchseco/controller
docker run -ti --rm --entrypoint /bin/bash searchseco/controller
root@cea3c05c0d8b:/# cat /controller/build/.env 
API_IPS=API_IPS=131.211.31.176?8003,131.211.31.179?8003,131.211.31.183?8003
```

So running the container fails:
```sh
docker run --rm --name controller-container -e github_token=xxxxx -e worker_name=xxxxx searchseco/controller
2022-09-14 06:55:01.644 (   0.006s) [controller      ]           commands.cpp:516   INFO| Starting a worker node with 4 cpu cores
2022-09-14 06:55:01.644 (   0.006s) [controller      ]         networking.cpp:196    ERR| E019 - No IPs found in .env file. IPs should be in format API_IPS=ip1?port1,ip2?port2
```

It would be useful to be able to set the `API_IPS` at runtime, for example:
```sh
docker run --rm --name controller-container -e github_token=xxxxx -e worker_name=xxxxx -e "API_IPS=138.201.216.223?8003,95.217.155.82?8003" searchseco/controller
```

A potential solution could use a bash script as the Dockerfile `ENTRYPOINT` to intercept configuration from the environment and write it to the `.env` file before calling `searchseco start`.

**Comment by slingerbv** [comment]
First and foremost: Thank you! We were looking at this bug for a long time and couldn't figure it out. It's looking like it's fixed now. 

But why would we make the IPs scriptable? Our fear has always been that someone starts inefficiently running their own DB cluster, making our work moot ;-).

**Comment by xendarboh** [comment]
I'm still getting to know the project to suggest solutions more supportive of the intentions.

As it is now, for a developer (or whoever) to build and use the docker image themselves, they must configure API_IPS so that implies it should be configured. And they have to figure out what values to use for API_IPS to connect to the official DB... I ran and extracted them from the published image, messy. So, perhaps an improvement would be to more completely remove it from awareness of others; either include it in the `.env` file under git control and remove it as a required step within the `README`, or update `README` to explain what value to use there, or something else. ?

As open source, humans will do what humans will do and maybe they don't have an incentive to run their own DB cluster unless the official one itself was deemed too inefficient, or too centralized, etc. Seems most would want to connect to the official DB so this issue could be about making that more effortless to do by default.

**Comment by abebeos** [comment]
hit on this annoying problem, too.

> Wait, wouldn't this be very easy? Shall I put a bounty on it?

should be quite easy, the (by @xendarboh ) suggested 

> `-e "API_IPS=138.201.216.223?8003,95.217.155.82?8003`"

should do the work

**Comment by slingerbv** [comment]
So... It's already implemented or should I put a bounty on it?

**Comment by abebeos** [comment]
@slingerbv  you can bounty this, suggesting $100 to do it quickly, $200 with a bit more extensive testing.

**Comment by abebeos** [comment]
@xendarboh , @slingerbv , after working a bit I have clarity:

API_IPS should be simply added to the config.txt. `.env. would be dropped.

**Comment by abebeos** [comment]
(besides simplicity and consistency, this allows for -e API_IPS on the command line)

**Comment by abebeos** [comment]
> API_IPS should be simply added to the config.txt. `.env. would be dropped.

starte this, but aborted, the code is a bit difficult to follow. Trying something else.

**Comment by abebeos** [comment]
fixed locally/private

- API_IPS can be passed via the system environment.
- Additionally: providing real-life/code examples for
  - efficient refactoring (no functional change) and 
  - rework (introduce a slight functional change wit very low risk).

Not pushing the results, see #90
